jenkins_url: http://localhost:8080/

defaults:
  github:
    protocol: ssh                                           # SSH or HTTP
    credentials: my-gh-creds                                # Not required for public repos, this should
                                                            # be ID of Jenkins credentials
                                                            # https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin
  bitbucket:
    credentials: my-bb-creds                               # Credentials to use for authorization with BitBucket

jobs:
 - name: GenericGitBuild
   folder: dsl-doc
   git:
     credentials: myGitCreds                                # Credentials with 'myGitCreds' are required in Jenkins credentials store
     url: git@github.com:myOrg/myApp.git                    # Github is used only as an example, can by any git repo
     branch: feature/new-hot-feature                        # Branch name
     repo_target_dir: appcode                               # Checkout in workspace sub-directory

 - name: GenericGitBuildWithRefspec
   folder: dsl-doc
   git:
     url: https://github.com/nodejs/readable-stream         # Public repo - credentials property is not required
     branch: tags/v2.0.4                                    # Build specific tag

 - name: ParallelJob
   concurrentBuild: true

 - name: JobWith10BuildsKept
   folder: dsl-doc
   discardBuilds:
     buildsToKeep: 10                                       # Store latest 10 builds

 - name: JobWith10ArtifactsKept
   folder: dsl-doc
   discardBuilds:
     artifactBuildsToKeep: 10                               # Store latest 10 artifacts

 - name: JobWithBuildsKept10Days
   folder: dsl-doc
   discardBuilds:
     daysToKeep: 10                                         # Store builds for 10 days

 - name: JobWithArtifactsKept10Days
   folder: dsl-doc
   discardBuilds:
     artifactDaysToKeep: 10                                 # Store artifacts for 10 days

 - name: MyLabeledJob
   folder: dsl-doc
   labels:
     - MavenBuild

 - name: MyJobWithParameters
   folder: dsl-doc
   parameters:
     param1: value1                                        # default value is 'value1'
     param2: ''                                            # no default value
     deployment: true                                      # Boolean parameters have true / false value
     deploymentEnvironment:                                # Choice parameter
       - dev
       - stage
       - prod

 - name: MyJobWithParametersDefinedAsMap
   folder: dsl-doc
   parameters:                                            # Define parameters as map of maps
     param1:                                              # Parameter name will be uppercased
       default: true                                      # Default value
       description: 'Deploy artifact?'                    # Parameter description

     param2:
       description: 'If no default value provided, empty string shall be used'

     choice_param:
       options:                                           # Define options for choice parameter
        - option1
        - option2
        - option3
       description: 'Use dropdown form to select value for CHOICE_PARAM'

 - name: MyJobWithDescription
   folder: dsl-doc
   description: My Job Description

 - name: CiinaboxGithub
   folder: dsl-doc
   repo: base2Services/ciinabox                             # GitHub repo, with owner
   branch: master                                           # Branch to build

 - name: CiinaboxGithub-PullRequest
   folder: dsl-doc
   repo: base2Services/ciinabox                             # GitHub repo, with owner

 - name: BitbucketJob
   folder: dsl-doc
   bitbucket:
     push: true                                             # Trigger build upon BB push
     cron: "* * * * *"                                      # Poll SCM for changes
     repo: nlstevenen/java-experimenting-with-java-8-features # BB repo to pull sources from
     branch: master                                         # Which branch to build
     repo_target_dir: app_code                              # Checkout in workspace sub-folder

 - name: SetBuildDesciption
   folder: dsl-doc
   repo: base2Services/ciinabox                             # GitHub repo, with owner
   build_description: My Build ${CUSTOM_VAR}                # Sets build description

 - name: SetBuildDesciptionFull
   folder: dsl-doc
   repo: base2Services/ciinabox                             # GitHub repo, with owner
   build_description:
     description: My Build ${CUSTOM_VAR}                    # Sets build description
     descriptionForFailed: Failed ${CUSTOM_VAR}             # Sets build description on failure
     regularExpression: Uploading[^\s]* ([^\s]*)            # Regex will be applied to each line in the build log
     regularExpressionForFailed: Failed [^\s]* ([^\s]*)     # Regex will be applied to each line in the build log on failure
