version: "3"
services:
  jenkins:
    container_name: ciinabox-jenkins
    image: base2/ciinabox-jenkins:2
    environment:
      - JAVA_OPTS=-Duser.timezone=Australia/Melbourne
    ports:
      - "8080:8080"
    links:
      - jenkins-slave:jenkins-docker-dind-slave
    volumes:
      - ./jenkins-data:/var/jenkins_home

  jenkins-slave:
    container_name: ciinabox-jenkins-slave
    image: base2/ciinabox-docker-slave:latest
    privileged: true
    environment:
      - JAVA_OPTS=-Duser.timezone=Australia/Melbourne
      - RUN_DOCKER_IN_DOCKER=1
    volumes:
      - $HOME/.aws/:/home/jenkins/.aws
